base_images:
  ocp_builder_rhel-8-golang-1.19-openshift-4.15:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.19-openshift-4.15
build_root:
  from_repository: true
images:
- dockerfile_literal: |-
    FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.15
    COPY . .
    RUN chgrp -R 0 /go && \
    chmod -R g=u /go
    RUN mkdir -p /.cache
    RUN chgrp -R 0 /.cache && \
    chmod -R g=u /.cache
  inputs:
    ocp_builder_rhel-8-golang-1.19-openshift-4.15:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.15
  to: jenkins-runner
releases:
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.15.0-0
        stream: 4-stable
        upper: 4.16.0-0
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: jenkins-interop-ibmcloud
  cron: 0 6 25 10 *
  steps:
    cluster_profile: ibmcloud-cspi-qe
    env:
      BASE_DOMAIN: zstream.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        {
          "failure_rules":
            [
              {"step": "ipi-*", "failure_type": "all", "classification": "Infrastructure Provisioning - Cluster", "group": {"name": "cluster", "priority": 1}, "jira_additional_labels": ["!default"]},
              {"step": "gather-*", "failure_type": "all", "classification": "Other", "group": {"name": "cluster", "priority": 3}, "jira_additional_labels": ["!default"]},
              {"step": "openshift-*", "failure_type": "all", "classification": "Other", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
              {"step": "jenkins-smoke-tests", "failure_type": "pod_failure", "classification": "Test Execution", "group": {"name": "lp-tests", "priority": 1}, "jira_additional_labels": ["!default","interop-tests"]},
              {"step": "jenkins-smoke-tests", "failure_type": "test_failure", "classification": "Test Failure", "jira_project": "OCPBUGS", "group": {"name": "lp-tests", "priority": 1}, "jira_component": ["Jenkins"], "jira_affects_version": "4.15", "jira_additional_labels": ["!default","interop-tests"]}
            ],
          "success_rules":
            [
              {"jira_project": "CSPIT", "jira_additional_labels": ["!default"]}
            ]
        }
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.15-lp","self-managed-lp","jenkins-lp"]'
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
      FIREWATCH_FAIL_WITH_TEST_FAILURES: "true"
    test:
    - ref: jenkins-smoke-tests
    workflow: firewatch-ipi-ibmcloud
zz_generated_metadata:
  branch: release-4.15
  org: openshift
  repo: jenkins
  variant: jenkins-ocp4.15-lp-interop
