base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_literal: |
    FROM registry.access.redhat.com/ubi8/ubi

    ENV LANGUAGE='en_US:en'
    WORKDIR /tmp

    # ubi8 repos contain maven 3.5 and jdk 1.8; we need something newer
    RUN dnf install -y wget git zip unzip --setopt=install_weak_deps=False
    RUN wget -O sdkman.sh https://get.sdkman.io && /bin/bash sdkman.sh
    RUN source "/root/.sdkman/bin/sdkman-init.sh" && sdk install java 22.3.2.r17-mandrel && sdk install maven 3.8.7
    ENV SDKMAN_DIR=/root/.sdkman

    # install oc client
    ADD https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.13.0/openshift-client-linux-4.13.0.tar.gz oc.tar.gz
    RUN tar -xaf oc.tar.gz oc && mv oc /usr/local/bin/

    # these versions should be updated for every release
    ENV QUARKUS_BRANCH=2.13
    ENV QUARKUS_VERSION=2.13.7.Final-redhat-00003
    ENV QUARKUS_PLATFORM_GROUP_ID=com.redhat.quarkus.platform
    ENV QUARKUS_PLATFORM_ARTIFACT_ID=quarkus-bom

    ## List of projects to include in smoke test
    ENV PROJECTS=config,lifecycle-application,http/http-minimum,http/http-minimum-reactive,sql-db/sql-app,monitoring/microprofile-opentracing

    RUN chgrp -R 0 /var && chmod -R g=u /var

    RUN git clone --depth=1 -b ${QUARKUS_BRANCH} https://github.com/quarkus-qe/quarkus-test-suite.git tests
    WORKDIR /tmp/tests
    RUN chmod -R 777 /tmp/tests

    RUN mkdir --mode=777 /tmp/home
    ENV HOME=/tmp/home

    # maven settings for repository
    ADD settings.xml /tmp/home/.m2/settings.xml

    ADD --chmod=755 run.sh /tmp/tests/
    ADD --chmod=755 oc_login.sh /tmp/tests/
    # to debug on local
    # ADD --chmod=755 oc_login_local.sh /tmp/tests/oc_login.sh

    # test results are in $PROJECT/target/failsafe-reports/*.xml for every PROJECT in $PROJECTS.
    CMD ./oc_login.sh && source "/root/.sdkman/bin/sdkman-init.sh" && ./run.sh
  to: quarkus-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tests:
- as: quarkus-interop-aws
  cron: 0 6 * * 1
  remote_api: true
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        [
          {"step": "ipi-*", "failure_type": "all", "classification": "Infrastructure Provisioning - Cluster", "jira_project": "LPTOCPCI", "jira_epic":"LPTOCPCI-290"},
          {"step": "openshift-*", "failure_type": "all", "classification": "Other", "jira_project": "LPTOCPCI", "jira_epic":"LPTOCPCI-290"},
          {"step": "quarkus-collect-results", "failure_type": "pod_failure", "classification": "Test Execution", "jira_project": "LPTOCPCI", "jira_epic":"LPTOCPCI-290"},
          {"step": "quarkus-collect-results", "failure_type": "test_failure", "classification": "Test Failure", "jira_project": "LPTOCPCI", "jira_epic":"LPTOCPCI-290"}
        ]
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPTOCPCI
      FIREWATCH_JIRA_SERVER: https://issues.redhat.com
    test:
    - ref: quarkus-collect-results
    workflow: firewatch-ipi-aws
zz_generated_metadata:
  branch: main
  org: quarkus-qe
  repo: quarkus-test-suite
  variant: quarkus-ocp4.14-lp-interop
