base_images:
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
releases:
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.16.0-0
        stream: 4-stable
        upper: 4.17.0-0
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cost-management-interop-ibmcloud
  cron: 0 6 11 2 *
  steps:
    cluster_profile: ibmcloud-cspi-qe
    env:
      BASE_DOMAIN: zstream.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        {
          "failure_rules":
            [
              {"step": "insights-qe-iqe-*", "failure_type": "test_failure", "classification": "Cost Management Test Failure", "jira_project": "COST", "jira_assignee": "!default", "jira_additional_labels": ["!default","interop-tests"]},
              {"step": "insights-qe-iqe-*", "failure_type": "pod_failure", "classification": "Cost Management Test Execution", "jira_additional_labels": ["!default","interop-tests"]}
            ]
        }
      FIREWATCH_CONFIG_FILE_PATH: https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/ibm-ipi/lp-interop.json
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.16-lp","self-managed-lp","cost-management-lp"]'
      FIREWATCH_DEFAULT_JIRA_ASSIGNEE: dchorvat@redhat.com
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
    test:
    - ref: insights-qe-iqe-cost-management-plugin
    workflow: firewatch-ipi-ibmcloud
  timeout: 3h0m0s
zz_generated_metadata:
  branch: master
  org: insights-qe
  repo: iqe-cost-management-plugin
  variant: ocp4.16-lp-interop
