base_images:
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: docker-container-executor/Dockerfile
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: rhsso-runner
releases:
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.15.0-0
        stream: 4-stable
        upper: 4.16.0-0
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rhsso-interop-ibmcloud
  cron: 0 6 25 12 *
  steps:
    cluster_profile: ibmcloud-cspi-qe
    env:
      BASE_DOMAIN: zstream.interop.ccitredhat.com
      OCP_PROJECT_NAME: keycloak
      OPERATORS: |
        [
            {"name": "rhsso-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "keycloak", "operator_group": "rhsso-operator-group", "target_namespaces": "keycloak"}
        ]
    test:
    - ref: install-operators
    - ref: keycloak-qe-rhsso-tests
    workflow: ipi-ibmcloud
zz_generated_metadata:
  branch: main
  org: rhbk
  repo: interop-ocp-ci
  variant: rhsso-product-ocp4.15-lp-interop
