base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  kiali-cypress-tests-runner:
    name: kiali-cypress-tests
    namespace: ci
    tag: v1.65
  kiali-int-tests-runner:
    name: kiali-int-tests
    namespace: ci
    tag: v1.65
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: Dockerfile
  to: maistra-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: OCP_VERSION
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: servicemesh-interop-ibm
  cron: 0 6 25 10 *
  steps:
    cluster_profile: ibmcloud-cspi-qe
    env:
      BASE_DOMAIN: zstream.interop.ccitredhat.com
      OPERATORS: |
        [
            {"name": "elasticsearch-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "jaeger-product", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "kiali-ossm", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"},
            {"name": "servicemeshoperator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-operators"}
        ]
      RESOURCE_GROUP: zstream-ocp-interop
      SMCP_VERSION: "2.4"
      TEST_GROUP: interop
    test:
    - ref: install-operators
    - ref: servicemesh-maistra-test-tool-execute
    - ref: servicemesh-smcp-install
    - ref: servicemesh-kiali-int-tests-execute
    - ref: servicemesh-kiali-cypress-tests-execute
    workflow: ipi-ibmcloud
zz_generated_metadata:
  branch: main
  org: maistra
  repo: maistra-test-tool
  variant: servicemesh-ocp4.14.z-lp-interop
